# NumPy

1. NumPy = Numerical Python
2. Found by Travis Oliphant in 2008
3. It defines multiple dimensions of arrays helping in fst mathematical functions.
4. A fundamental package for scientific computing.
5. Works in domains of Linear Algebra, Matrices and Fourier Transformation.

# Arrays

1. Collection of items which are stored very in close memory locations.
2.  Contains fixed number of and same type of items.
3. Saves a lot of time and takes less space than usual lists

# Advantages of Arrays

1. Less memory to store data.
2. Used for creating n-dimensional arrays.
3. Makes it very easy to perform Mathematical Calculations.
4. Finding any element in NumPy arrays is easy.

In [1]:
import numpy as np

In [3]:
l1 = [10, 20, 30]
l2 = [40, 50, 60]
print(l1 + l2)  # This will concatenate the lists
print(l1 * 2)

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 10, 20, 30]


In [ ]:
l1 = np.array([10, 20, 30])
l2 = np.array([40, 50, 60])
print(l1 + l2)  # This will add the arrays element-wise
print(l1 * l2)   # This will multiply each element by the corresponding element

[50 70 90]
[ 400 1000 1800]


In [6]:
l1 = np.array([10, 20, 30])
l2 = 5
print(l1 + l2)  # This will add 5 to each element of the array
print(l1 * l2)  # This will multiply each element by 5

[15 25 35]
[ 50 100 150]


# Arrays vs Lists

1. List cannot perform Mathematical Operations, but Arrays can.
2. Arrays consume less memory than lists.
3. Arrays are faster than lists.
4. List can store different datatypes but arrays cannot.
5. In losts, one can have nested data with different sizes, but arrays cannot.
5. A list is easier to modify than array as it stores data individually.
6. It is easier to add or delete an element in list than in array.

In [10]:
# List
list1 = [[10, 20, 30],[50, 60]]
print(list1) #+ This will print a list of lists

[[10, 20, 30], [50, 60]]


In [ ]:
# Array
list1 = np.array([[10, 20, 30],[50, 60]])
print(list1) # This will gice an error because the inner lists have different lengths

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.