In [12]:
import numpy as np

In [13]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [14]:
arr.shape # (5,) It means the array has 5 elements in one dimension.

(5,)

In [15]:
arr.size # It returns the total number of elements in the array

5

In [16]:
arr.dtype # datatype of the array

dtype('int64')

In [17]:
arr.astype(float) # convert from int to float

array([10., 20., 30., 40., 50.])

In [18]:
arr1 = np.array([10.5, 20.5, 30.5, 40.5, 50.5])
print(arr1)

[10.5 20.5 30.5 40.5 50.5]


In [19]:
arr1.astype(int) # converts float to int

array([10, 20, 30, 40, 50])

In [20]:
len(arr) # It returns the number of elements in the array

5