In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2],[4,5]])
arr2 = np.array([[6,7],[8,9]])

In [4]:
print(arr1+arr2)
print(np.add(arr1, arr2))

[[ 7  9]
 [12 14]]
[[ 7  9]
 [12 14]]


In [5]:
print(arr1-arr2)
print(np.subtract(arr1, arr2))

[[-5 -5]
 [-4 -4]]
[[-5 -5]
 [-4 -4]]


In [6]:
print(arr1*arr2)
print(np.multiply(arr1, arr2))

[[ 6 14]
 [32 45]]
[[ 6 14]
 [32 45]]


In [22]:
print(arr1/arr2)
print(np.divide(arr1, arr2).astype(int))

[[0.16666667 0.28571429]
 [0.5        0.55555556]]
[[0 0]
 [0 0]]


In [14]:
a = np.array([[1,2,4,5]])
b = np.array([2])

print(a**b)
print(np.power(a, b))

[[ 1  4 16 25]]
[[ 1  4 16 25]]


In [18]:
a = [ 1, 4, 16, 25]
print(np.sqrt(a).astype(int))

[1 2 4 5]
