In [1]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate((a, b), axis=0))  # Concatenate along rows

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
print(np.vstack((a, b)))  # Vertical stack (equivalent to axis=0)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate((a, b), axis=1))  # Concatenate along columns

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [9]:
print(np.hstack((a, b)))  # Horizontal stack (equivalent to axis=1)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [14]:
ab = np.array([[10, 20, 30], [40, 50, 60]])
print(np.array_split(ab, 2))  # Split into 2 equal parts

[array([[10, 20, 30]]), array([[40, 50, 60]])]
