In [1]:
import numpy as np

In [13]:
a = np.array([[1,2,3,6],[8,10,4,0]])
print(np.sort(a)) # Sorts the array in ascending order

[[ 1  2  3  6]
 [ 0  4  8 10]]


In [10]:
b = np.array([1,2,3,6,4,8,7,5,9])
c = np.where(b % 2 == 0)
print(c)

(array([1, 3, 4, 5]),)


In [17]:
a = np.array([1,2,3,6])
print(np.searchsorted(a, 2))  # Returns the index where 2 should be inserted to maintain order

1


In [18]:
d = np.array([10,20,30,40,50])
e = np.array([False, True, False, True, False])
print(d[e])  # Returns elements of d where e is True

[20 40]


In [20]:
e = d > 30
f = d[e]
print(f)  # Returns elements of d that are greater than 30

[40 50]


In [22]:
g = d % 3 == 0
h = d[g]
print(h)  # Returns elements of d that are even

[30]
