In [3]:
import numpy as np

In [4]:
a = np.array([20, 40, 60, 80, 100])

In [13]:
print(np.sum(a))  # Sum of all elements
print(np.min(a))  # Minimum value
print(np.max(a))  # Maximum value
print(np.size(a))  # Number of elements
print(np.mean(a))  # Mean value
print(np.cumsum(a))  # Cumulative sum
print(np.cumprod(a))  # Cumulative product

300
20
100
5
60.0
[ 20  60 120 200 300]
[       20       800     48000   3840000 384000000]


In [21]:
price = np.array([100, 200, 300, 400, 500])
quantity = np.array([1, 2, 3, 4, 5])
print(price * quantity)  # Element-wise multiplication
c = np.cumprod([price, quantity], axis=0)  # Cumulative product of price * quantity
print(c[1].sum)

[ 100  400  900 1600 2500]
<built-in method sum of numpy.ndarray object at 0x0000027CEC732B50>
